Added javascript exercises 1 and 2 for day 1
madhanramu/cdp pull request #112
Opened 2022-09-16 18:34 UTC by charlesnummer

Added 2 javascript exercises and merged with main.

2022-09-16 20:27 UTC, charlesnummer commented
<img width="555" alt="JavascriptExercise1" src="https://user-images.githubusercontent.com/113386028/190727246-4f18b567-b99c-4277-869d-ff07be78e15a.png">
<img width="570" alt="JavascriptExercise2" src="https://user-images.githubusercontent.com/113386028/190727251-4bd67014-3079-49d7-b051-2f54227e4c95.png">

2022-09-19 19:45 UTC, charlesnummer commented
![JavascriptExercise4Multiply](https://user-images.githubusercontent.com/113386028/191102511-afdd1305-1190-4f37-a6a1-12f1e98985a
![JavascriptExercise4Divide](https://user-images.githubusercontent.com/113386028/191102524-ff452842-ca9a-4c73-bb5a-aee17f9cc24b.png)
3.png)
![JavascriptExercise5](https://user-images.githubusercontent.com/113386028/191102529-6d8ccaf7-379a-40af-9ba6-853b0e0e7648.png)

2022-09-19 19:47 UTC, charlesnummer commented
![JavascriptExercise4Multiply](https://user-images.githubusercontent.com/113386028/191102865-a9b31e6b-fae5-45c9-84d8-33809e6edfe4.png)

2022-09-19 19:49 UTC, charlesnummer commented
![JavascriptUdemy](https://user-images.githubusercontent.com/113386028/191103588-c2d23f5c-b338-4ae7-b064-4a3682fbc8fc.png)

2022-09-20 23:49 UTC, madhanramu requested changes

2022-09-20 23:49 UTC, madhanramu commented on charlesnummer/javascript/js2-exercise4.html
> +                document.getElementById("final").textContent = final;
good

2022-09-20 23:49 UTC, madhanramu commented on charlesnummer/javascript/js2-exercise5.html
> +                <li>Product 1 <button onclick="add1()">Add to wishlist</button></li>
use a single method add() for all the 3 products. On click of "Add to Wishlist". The element should get removed from "Products" and should get added to "Wishlist"

2022-09-21 15:17 UTC, merged