Added Javascript exercises from day 1
madhanramu/cdp pull request #114
Opened 2022-09-16 18:57 UTC by sydneynguyen912

Both javascript exercises finished in this PR.

2022-09-16 20:04 UTC, sydneynguyen912 commented
![image](https://user-images.githubusercontent.com/113386022/190723992-4b217b47-d668-450e-ad1a-c5e47a764332.png)
![image](https://user-images.githubusercontent.com/113386022/190724023-5ffa80e9-c128-4d0f-b34d-bee8281f4953.png)

2022-09-16 20:06 UTC, sydneynguyen912 commented
![image](https://user-images.githubusercontent.com/113386022/190724352-13c2cdd7-cbca-48e9-ab45-b4bff507870b.png)

2022-09-19 18:24 UTC, sydneynguyen912 commented
![image](https://user-images.githubusercontent.com/113386022/191088009-24023310-a1e8-4929-9c93-62021e3b7c29.png)



![image](https://user-images.githubusercontent.com/113386022/191087800-a2a9b1cc-6e98-4881-9571-4a5035d47732.png)

2022-09-19 19:03 UTC, sydneynguyen912 commented
Finished JS Udemy course: screenshot 
![image](https://user-images.githubusercontent.com/113386022/191095334-4981fd75-3bd2-49a4-a921-314824d72d70.png)

2022-09-19 22:27 UTC, madhanramu requested changes

2022-09-19 22:27 UTC, madhanramu commented on sydneynguyen/css/css/holygrail.css
> +    background-color: rgb(185, 185, 185);
use hex values for colors

2022-09-19 22:27 UTC, madhanramu commented on sydneynguyen/css/css/holygrail.css
> +    flex: 1;
flex is is the property of flex item. should not be using for container

2022-09-19 22:27 UTC, madhanramu commented on sydneynguyen/css/css/holygrail.css
> +    background-color: rgb(171, 161, 181);
use hex value instead of rgb.

2022-09-19 22:27 UTC, madhanramu commented on sydneynguyen/js/js_findNearest.js
> +function findNearestValueTo100() {
good

2022-09-20 23:33 UTC, madhanramu approved these changes

2022-09-21 13:03 UTC, merged