Adding new gitignore, variables exercise, and find value nearest to 100
madhanramu/cdp pull request #116
Opened 2022-09-16 19:17 UTC by Lana-Butorovic

I am updating my .gitignore file and both of the js day 1 exercises.

2022-09-16 20:05 UTC, Lana-Butorovic commented
<img width="491" alt="Screen Shot 2022-09-16 at 4 03 58 PM" src="https://user-images.githubusercontent.com/109984701/190724229-361caf38-5e7e-4cc4-8492-2868bc2e89bd.png">

2022-09-19 22:33 UTC, madhanramu requested changes

2022-09-19 22:33 UTC, madhanramu commented on lanabutorovic/js/exercise1-variables.js
> +let total = 2 * myNumber;
add console.log for both myNumber and fullname

2022-09-20 12:47 UTC, Lana-Butorovic commented
Added console log: 

<img width="491" alt="Screen Shot 2022-09-20 at 8 47 12 AM" src="https://user-images.githubusercontent.com/109984701/191261474-1a6b6e21-4fc5-45b4-995b-819e3240f3aa.png">

2022-09-20 16:57 UTC, merged