done with Javascript exercises
madhanramu/cdp pull request #119
Opened 2022-09-16 20:28 UTC by codewithmanny

I am done with both javascript exercises and attached is a picture of the output.

![javascript exercise](https://user-images.githubusercontent.com/113386282/190727401-4fc690f3-adb4-4d85-a065-851d554fb68c.jpg)

2022-09-19 17:51 UTC, rbongiorno-ey requested changes

2022-09-19 17:51 UTC, rbongiorno-ey commented on emmanuelagyei/js/variable.js
> +
The requirement here is to multiply y by 2 and output the result.

2022-09-19 17:51 UTC, rbongiorno-ey commented on emmanuelagyei/js/variable.js
> +
You should be looking for the absolute difference Math.abs(n - 100).

2022-09-19 17:51 UTC, rbongiorno-ey commented on emmanuelagyei/js/variable.js
> +    return a + "is nearest"
You might want to check for a1==b1, at which a _and_ b are the same distance from 100.

2022-09-19 19:16 UTC, codewithmanny commented on emmanuelagyei/js/variable.js
> +
fixed . please check line 26 and 27

2022-09-19 22:16 UTC, madhanramu approved these changes

2022-09-20 19:59 UTC, rbongiorno-ey approved these changes

2022-09-20 22:23 UTC, merged