Emmanuel jsday2 javascript assignments
madhanramu/cdp pull request #130
Opened 2022-09-20 15:17 UTC by codewithmanny

Attached are Images of the outputs for both javascript assignment and udemy screenshot

![sampleform](https://user-images.githubusercontent.com/113386282/191297463-f87dcf47-1d32-41ad-99e4-f7f5f4ebe1c3.jpg)
![products](https://user-images.githubusercontent.com/113386282/191297534-4d3fe408-8612-42e9-8318-745322a10b1b.jpg)
![udemycompleted](https://user-images.githubusercontent.com/113386282/191297582-2402cdb4-705b-4019-b56b-2aba7fdd6ceb.jpg)

2022-09-20 16:35 UTC, rbongiorno-ey requested changes

2022-09-20 16:35 UTC, rbongiorno-ey commented on emmanuelagyei/js/variable.js
> +
for fullname, you need to add the space (" ") between the first and last names.

2022-09-20 16:35 UTC, rbongiorno-ey commented on emmanuelagyei/js/variable.js
> +console.log(fullName + y);
This should output y multiplied by 2

2022-09-20 16:35 UTC, rbongiorno-ey commented on emmanuelagyei/js/variable.js
> +
You are trying to get the nearest to 100, and you have to factor in a negative 'distance'.
You should use the Math library - Math.abs(value) to get the absolute difference between the number and 100.

2022-09-20 16:35 UTC, rbongiorno-ey commented on emmanuelagyei/js/variable.js
> +    return a + "is nearest"
This is true if a1 is less than b2.  But what if a1 and b1 are equal, then both numbers are equidistant from 100.

2022-09-20 16:35 UTC, rbongiorno-ey commented on emmanuelagyei/Js-day2/products.html
> +    <li>Product 3 <input type="text" name="" id="" value="Add to wishlist"> </li>
The inputs should be buttons, that when clicked on, will add "Product #" to the Wishlist.

2022-09-20 16:35 UTC, rbongiorno-ey commented on emmanuelagyei/Js-day2/products.html
> +    <input type="text" name="" id="" value="Add to wishlist">
This should be a display area which contains the Wishlist which is built out as you click the product add buttons above.

2022-09-20 20:00 UTC, rbongiorno-ey approved these changes
Approve, assuming the variables.js from PR#119 will be the final version.

2022-09-20 22:25 UTC, madhanramu commented on emmanuelagyei/Js-day2/products.html
> +        let li = document.createElement('li');
If you add the item to Wishlist , the should be remove from products

2022-09-22 12:55 UTC, madhanramu approved these changes

2022-09-22 12:55 UTC, madhanramu commented on emmanuelagyei/Js-day2/products.html
> +                li.innerText = item;
Code Indentation. Indent the code properly.

2022-09-22 12:56 UTC, merged