Adding java exercises for day 1
madhanramu/cdp pull request #135
Opened 2022-09-20 20:12 UTC by Lana-Butorovic

<img width="1440" alt="Screen Shot 2022-09-20 at 4 08 42 PM" src="https://user-images.githubusercontent.com/109984701/191355048-09988db2-ec0b-47b3-aa23-963422136697.png">

<img width="1440" alt="Screen Shot 2022-09-20 at 4 08 10 PM" src="https://user-images.githubusercontent.com/109984701/191355112-431e8917-0ddb-4fd8-9997-402dad1e1f78.png">

2022-09-21 19:50 UTC, Lana-Butorovic commented
Adding screenshots for modified 1-4 and exercises 5 and 6 

<img width="1440" alt="Screen Shot 2022-09-21 at 3 46 22 PM" src="https://user-images.githubusercontent.com/109984701/191596659-05551fc8-456d-4a23-815f-0a9faebb3bb7.png">

<img width="1440" alt="Screen Shot 2022-09-21 at 3 47 00 PM" src="https://user-images.githubusercontent.com/109984701/191596764-22aa06e7-1c3b-4d83-be60-e805bb43dd8e.png">


<img width="1440" alt="Screen Shot 2022-09-21 at 3 47 34 PM" src="https://user-images.githubusercontent.com/109984701/191597045-493183aa-5867-404c-8c55-8cecf1933d48.png">


<img width="1440" alt="Screen Shot 2022-09-21 at 3 48 01 PM" src="https://user-images.githubusercontent.com/109984701/191596968-80eccf7f-785c-40d4-b5f2-763edb36418b.png">
tent.com/109984701/191596891-96905263-64e1-4a8c-affc-a779f13ade02.png">

<img width="1440" alt="Screen Shot 2022-09-21 at 3 49 11 PM" src="https://user-images.githubusercontent.com/109984701/191597202-06b80843-0aef-4c9e-aa9e-0d85a3226b3b.png">

<img width="1440" alt="Screen Shot 2022-09-21 at 3 49 48 PM" src="https://user-images.githubusercontent.com/109984701/191597291-99bb848f-6e83-4878-a5e6-6cd1d5f965e4.png">

2022-09-21 20:32 UTC, Lana-Butorovic commented
Adding exercise 7 screenshot 

<img width="1440" alt="Screen Shot 2022-09-21 at 4 32 03 PM" src="https://user-images.githubusercontent.com/109984701/191604657-ba392d85-89c7-4e6a-ad00-b961d0144bc6.png">

2022-09-23 19:34 UTC, Lana-Butorovic commented
Adding screenshots for exercises 8-10

<img width="696" alt="Screen Shot 2022-09-23 at 3 28 33 PM" src="https://user-images.githubusercontent.com/10998470

<img width="694" alt="Screen Shot 2022-09-23 at 3 29 02 PM" src="https://user-images.githubusercontent.com/109984701/192043861-1007dd20-9060-490a-bbea-7b8aa5f8020e.png">
1/192043853-2a262e1d-f473-463e-a73f-f6dd67ff55d0.png">

<img width="789" alt="Screen Shot 2022-09-23 at 3 31 31 PM" src="https://user-images.githubusercontent.com/109984701/192043869-522b826e-616e-4988-af1b-887a32e8e54d.png">

<img width="791" alt="Screen Shot 2022-09-23 at 3 31 49 PM" src="https://user-images.githubusercontent.com/109984701/192043887-6fe14459-7c0a-486a-bed3-b395ee445acf.png">

2022-09-26 17:29 UTC, Lana-Butorovic commented
Adding for exercise 11 - screenshot with all tests passing 

<img width="871" alt="Screen Shot 2022-09-26 at 1 28 35 PM" src="https://user-images.githubusercontent.com/109984701/192342174-c9e2e671-b5fb-483c-a33b-fcbff572b3a8.png">

2022-09-26 17:54 UTC, PieterSandwalker commented on lanabutorovic/java/exercise5.java
> +            this.rollNum = 3;
rollMun should be set to r

2022-09-26 18:54 UTC, PieterSandwalker requested changes
A lot of smart implementations, and a couple of mistypes that can be quickly fixed. A couple of the exercises ask for Constructors in the implementations, but I did not see them in use until Exercise 11, make sure you're using those whenever possible. Message me if you need clarification or help

2022-09-26 18:54 UTC, PieterSandwalker commented on lanabutorovic/java/exercise6.java
> +
Please use a Constructor method to set the length and breadth. e.g.: 
`public Rectangle(length, breadth) { 
/* Your code here */
}`

2022-09-26 18:54 UTC, PieterSandwalker commented on lanabutorovic/java/exercise6.java
> +
Lines 23, 26, and 29 will end up moved or deleted depending on how you implement this

2022-09-26 18:54 UTC, PieterSandwalker commented on lanabutorovic/java/exercise7.java
> +    }
Replace or call with a Constructor

2022-09-26 18:54 UTC, PieterSandwalker commented on lanabutorovic/java/exercise7.java
> +        }
Replace or call this with a Constructor.
Hint: look into super() method

2022-09-26 18:54 UTC, PieterSandwalker commented on lanabutorovic/java/exercise7.java
> +        BookTest1.setSpecialBookDetails(2);
These lines should be deleted with proper Constructors

2022-09-26 18:54 UTC, PieterSandwalker commented on lanabutorovic/java/MapDemo.java
> +            System.out.println(isMapUnique(map));
Print “The Map is unique” if true, “the Map is not unique” if false

2022-09-26 18:54 UTC, PieterSandwalker commented on lanabutorovic/java/exercise9.java
> +
Mistype: Forgot to print reverse words

2022-09-26 18:54 UTC, PieterSandwalker commented on lanabutorovic/java/exercise9.java
> +    }
Capitalize plurals, but also print all other words as well

2022-09-26 18:54 UTC, PieterSandwalker commented on lanabutorovic/java/exercise9.java
> +            pluralsDel.add(example.toUpperCase());
Don't need to capitalize for this one

2022-09-26 18:54 UTC, PieterSandwalker commented on lanabutorovic/java/exercise10.java
> +        }
What happens if you run out of integers on one of the lists?

2022-09-26 18:54 UTC, PieterSandwalker commented on lanabutorovic/java/exercise11/ShoppingCart.java
> +    }
These need to be a single method. You must assume you do not know if it will be successful beforehand.
Hint: Look at the potential return types for ArrayList's remove method

2022-09-26 18:54 UTC, PieterSandwalker commented on lanabutorovic/java/exercise11/exercise11.java
> +
Optional: Main method is not necessary because you're using the test file to interact with your objects

2022-09-26 23:23 UTC, Lana-Butorovic commented on lanabutorovic/java/exercise10.java
> +        }
That's why it's inside the while loop - while(i1 < array1Size || i2 < array2Size)

Doesn't this resolve it?

2022-09-27 00:14 UTC, PieterSandwalker requested changes
All changes approved, just add that new part of exercise 11

2022-09-27 12:42 UTC, Lana-Butorovic commented
@PieterSandwalker thank you for your feedback - is this the change you are referring to? Fixed that issue - only have one removeProduct() method now, you can see the test passing below

<img width="1061" alt="Screen Shot 2022-09-27 at 8 41 35 AM" src="https://user-images.githubusercontent.com/109984701/192529166-a1f6e7cf-b940-4001-8afc-495cae7ee062.png">

2022-09-27 12:48 UTC, PieterSandwalker approved these changes
All feedback fixed

2022-09-27 19:51 UTC, madhanramu requested changes

2022-09-27 19:51 UTC, madhanramu commented on lanabutorovic/java/exercise9.java
> +public class exercise9 {
Have your class name in Title case

2022-09-27 19:51 UTC, madhanramu commented on lanabutorovic/java/exercise7.java
> +        SpecialEditionBook BookTest1 = new SpecialEditionBook(4,"Harry Potter",20, 5);
Get the Book values from the users
use  Book BookTest1 = new SpecialEditionBook(4,"Harry Potter",20, 5);

2022-09-27 19:51 UTC, madhanramu commented on lanabutorovic/java/exercise6.java
> +        Scanner scanner1 = new Scanner(System.in);
use only one Scanner object to get both the values

2022-09-27 19:51 UTC, madhanramu commented on lanabutorovic/java/exercise5.java
> +        studentDemo.setStudDetails(1, "Lana", 5, 5, 5);
take the values from the user

2022-09-27 19:51 UTC, madhanramu commented on lanabutorovic/java/exercise4.java
> +        Scanner scanner1 = new Scanner(System.in);
use only one scanner object

2022-09-27 19:51 UTC, madhanramu commented on lanabutorovic/java/exercise4.java
> +        System.out.println("Enter the number you would like to add.");
what happens if I enter a invalid number "XYz"

2022-09-27 19:51 UTC, madhanramu commented on lanabutorovic/java/exercise2.java
> +    public static String exerciseWord1(String word, int number) {
provide proper meaningful name to this method 
"exerciseWord1" not a correct method name

2022-09-27 19:51 UTC, madhanramu commented on lanabutorovic/java/exercise11/exercise11Test.java
> +   @Test
add Comments on top of the method to indicate what you are testinfg

2022-09-27 19:51 UTC, madhanramu commented on lanabutorovic/java/exercise10.java
> +import java.util.Scanner;
add the problem statement as javadoc

2022-09-28 12:38 UTC, merged