Tung Nguyen - finished all java day 2 exercises + screenshots of demo and added pro…
madhanramu/cdp pull request #150
Opened 2022-09-21 19:10 UTC by tunggnguyen

1. Finished all exercises from java day 2 with screenshots.
2. Added problem descriptions for exercises from yesterday

2022-09-22 20:07 UTC, myolap approved these changes

2022-09-22 21:49 UTC, madhanramu requested changes

2022-09-22 21:49 UTC, madhanramu commented on tungnguyen/java/BookTest.java
> +        SpecialEditionBook tempBook2 = new SpecialEditionBook(id, name, random.nextInt(1000), 100);
you need to get the discount from the user.

2022-09-22 21:49 UTC, madhanramu commented on tungnguyen/java/Rectangle.java
> +    private int lengthOf;
use double

2022-09-22 21:49 UTC, madhanramu commented on tungnguyen/java/Rectangle.java
> +        return lengthOf * widthOf;
how the multiplication of two ints result in double. use double for length and width

2022-09-22 21:49 UTC, madhanramu commented on tungnguyen/java/Student.java
> +    public int calculateTotal() {
make it private

2022-09-22 21:49 UTC, madhanramu commented on tungnguyen/java/Day1Exercises.java
>      public static void main(String[] args) {
Good work on this

2022-09-27 23:51 UTC, madhanramu approved these changes

2022-09-27 23:58 UTC, merged