Java exercises 5-7
madhanramu/cdp pull request #151
Opened 2022-09-21 20:53 UTC by sydneynguyen912

2022-09-21 20:55 UTC, sydneynguyen912 commented
exercise 5: 
![image](https://user-images.githubusercontent.com/113386022/191608451-9db95f4c-39d8-4e75-9371-73ade02af29b.png)

exercise 6: 
![image](https://user-images.githubusercontent.com/113386022/191608533-fc4e8656-05d5-4221-a6f5-96663b5b8f48.png)

exercise 7: 
![image](https://user-images.githubusercontent.com/113386022/191607118-4852af87-9d2c-461a-8ad4-b20918446a5c.png)

2022-09-21 20:57 UTC, saitj99 approved these changes

2022-09-22 20:00 UTC, madhanramu requested changes
Add description and sc

2022-09-22 20:00 UTC, madhanramu commented on sydneynguyen/java_exercises/BookTest.java
> +            Book newBook = new Book(id, name, price);
declare `Book newBook` outside if block;
initialize here  `newBook = new Book(id, name, price);`

2022-09-22 20:00 UTC, madhanramu commented on sydneynguyen/java_exercises/BookTest.java
> +            SpecialEditionBook newBook = new SpecialEditionBook(id, name, price, discount);
declare `Book newBook` outside if block;
initialize here  `newBook =  new SpecialEditionBook(id, name, price, discount);`

2022-09-22 20:00 UTC, madhanramu commented on sydneynguyen/java_exercises/Rectangle.java
> +        return length * breadth;
how multiplication of two ints will result in double?

2022-09-22 20:00 UTC, madhanramu commented on sydneynguyen/java_exercises/Rectangle.java
> +    int length;
change int to double

2022-09-22 21:41 UTC, madhanramu approved these changes

2022-09-23 13:15 UTC, merged