reordered files and submitting java exercises 5, 6, and 7
madhanramu/cdp pull request #163
Opened 2022-09-22 21:06 UTC by AkhilRey

Reordered files into each exercise having its own folder. Also submitting screenshots of Java exercises 5, 6, and 7. Screenshots are in each folder, but also adding to this comment. 

<img width="960" alt="java1_exercise5" src="https://user-images.githubusercontent.com/113386160/191850924-51e0cf2e-de40-48ed-ba51-70c9558b89c0.PNG">
<img width="960" alt="java1_exercise6" src="https://user-images.githubusercontent.com/113386160/191850949-7b42902a-b42b-44ae-8fe5-a76da1c5c009.PNG">
<img width="960" alt="java2_exercise7pt1" src="https://user-images.githubusercontent.com/113386160/191850984-1879f384-d08b-46f3-b38d-136f9dee060f.PNG">
<img width="960" alt="java2_exercise7pt2" src="https://user-images.githubusercontent.com/113386160/191850986-13f19820-a1ee-40e4-89ff-7a01e31fa0d0.PNG">
<img width="960" alt="java2_exercise7pt3" src="https://user-images.githubusercontent.com/113386160/191850988-7ff7cee3-1be3-479c-b4de-ccd8830c7e7d.PNG">
<img width="960" alt="java2_exercise7pt4" src="https://user-images.githubusercontent.com/113386160/191850990-4eecc008-64a0-4a34-be16-1d1a698d996c.PNG">
<img width="960" alt="java2_exercise7pt5" src="https://user-images.githubusercontent.com/113386160/191850992-eafaad9e-78db-422e-81ca-4868fb8726f6.PNG">

2022-09-23 15:40 UTC, myolap approved these changes

2022-09-27 17:45 UTC, madhanramu requested changes

2022-09-27 17:45 UTC, madhanramu commented on akhilraghu/java/java3_exercise8/MapDemo.java
> +package cdp.akhilraghu.java.java3_exercise8; // package
Add Problem statement as a java doc for all the files
/**
* The HelloWorld program implements an application that
* simply displays "Hello World!" to the standard output.
*
*/

2022-09-27 19:28 UTC, madhanramu requested changes

2022-09-27 19:28 UTC, madhanramu commented on akhilraghu/java/java4_exercise11/test/ShoppingCartTest.java
> +        double currentBalance = 0.99 + 1.99;
you should have the actual value here instead of doing any operation. Just have the actual expected result.

2022-09-27 19:28 UTC, madhanramu commented on akhilraghu/java/java4_exercise11/test/ShoppingCartTest.java
> +        Assertions.assertEquals(test.getNumItems(), numBefore + 1);
assertEquals(expected, actual);
expected should be a exact value instead of numBefore + 1

2022-09-27 19:28 UTC, madhanramu commented on akhilraghu/java/java4_exercise11/test/ShoppingCartTest.java
> +        double currentBalance = 0.99 + 1.99;
assertEquals(expected, actual);

2022-09-27 19:28 UTC, madhanramu commented on akhilraghu/java/java4_exercise11/test/ShoppingCartTest.java
> +        Assertions.assertEquals(test.getNumItems(),1);
assertEquals(expected, actual);

2022-09-27 19:28 UTC, madhanramu commented on akhilraghu/java/java4_exercise11/test/ShoppingCartTest.java
> +        Assertions.assertEquals(test.removeItem(banana),"The item you are trying to remove is not in your cart.");
assertEquals(expected, actual);

2022-09-27 19:28 UTC, madhanramu commented on akhilraghu/java/java4_exercise11/test/ShoppingCartTest.java
> +        Assertions.assertEquals(test.getNumItems(), 0);
assertEquals(expected, actual);

2022-09-27 19:28 UTC, madhanramu commented on akhilraghu/java/java4_exercise11/test/ShoppingCartTest.java
> +        Assertions.assertEquals(test.shoppingList.size(), 0);
assertEquals(expected, actual);

2022-09-27 19:28 UTC, madhanramu commented on akhilraghu/java/java3_exercise9/ReadingFiles.java
> +public class ReadingFiles { // create class ReadinFiles
Change the name to FileReader

2022-09-27 21:58 UTC, madhanramu commented on akhilraghu/java/java2_exercise7/BookTest.java
> +package cdp.akhilraghu.java.java2_exercise7; // package info
good work here in the exercise

2022-09-27 23:14 UTC, madhanramu approved these changes

2022-09-27 23:38 UTC, merged