rianboutin-mysqldb-day1
madhanramu/cdp pull request #184
Opened 2022-09-27 13:13 UTC by rbEY22

<img width="954" alt="DB2" src="https://user-images.githubusercontent.com/113386144/192535832-3b26398f-f991-4426-9fb2-f3d3d2fb9b4a.PNG">
<img width="271" alt="DB3" src="https://user-images.githubusercontent.com/113386144/192535837-5242fb29-d3e1-46b3-a705-36cb0bb72f8d.PNG">
<img width="954" alt="DB4" src="https://user-images.githubusercontent.com/113386144/192535840-93fac0fa-3dfe-43b5-b040-4db59fe599c3.PNG">
<img width="951" alt="DB5" src="https://user-images.githubusercontent.com/113386144/192535841-ff18e70a-7331-40ce-ba39-554f48456e63.PNG">
<img width="955" alt="DB6" src="https://user-images.githubusercontent.com/113386144/192535845-c939dd9c-5c92-40f8-aa6d-34c4c4e7a96a.PNG">
<img width="261" alt="udemy1" src="https://user-images.githubusercontent.com/113386144/192535848-137f98a7-4726-404c-a463-e0860c106417.PNG">
<img width="952" alt="DB1" src="https://user-images.githubusercontent.com/113386144/192535851-e2e2ff14-6cb0-495a-b70e-d99e20b62531.PNG">

2022-09-28 23:40 UTC, rbongiorno-ey requested changes
Just 2 issues, which seem to be common mistakes.

2022-09-28 23:40 UTC, rbongiorno-ey commented on rianboutin/db/queries.sql
> +SELECT * FROM order_line WHERE item_number BETWEEN 1 AND 200 OR item_number > 1000 AND item_cost NOT IN (1000,2000,3000) OR orderno != 1000;
The WHERE clause needs parenthesis.
WHERE (firstcond) OR (secondcond)
You have condA AND condB OR condC AND condD which will evaluate left to right.

2022-09-28 23:40 UTC, rbongiorno-ey commented on rianboutin/db/queries.sql
> +SELECT * FROM clients WHERE name = 'EY';
This should check if the name contains EY.  You need to use LIKE instead of equals, and put in the % wildcards.  And you need a sample name that will provide a result, like "Shelley's"

2022-09-29 13:22 UTC, rbEY22 commented on rianboutin/db/queries.sql
> +SELECT * FROM order_line WHERE item_number BETWEEN 1 AND 200 OR item_number > 1000 AND item_cost NOT IN (1000,2000,3000) OR orderno != 1000;
UPDATE:
SELECT * FROM order_line WHERE item_number ((BETWEEN 1 AND 200) OR (item_number > 1000)) AND ((item_cost NOT IN (1000,2000,3000)) OR (orderno != 1000));

2022-09-29 13:32 UTC, rbEY22 commented on rianboutin/db/queries.sql
> +SELECT * FROM order_line WHERE item_number BETWEEN 1 AND 200 OR item_number > 1000 AND item_cost NOT IN (1000,2000,3000) OR orderno != 1000;
![image](https://user-images.githubusercontent.com/113386144/193045299-ed7cf949-2912-46cb-8a64-a8c421c7c2af.png)

2022-09-29 13:32 UTC, rbEY22 commented on rianboutin/db/queries.sql
> +SELECT * FROM order_line WHERE item_number BETWEEN 1 AND 200 OR item_number > 1000 AND item_cost NOT IN (1000,2000,3000) OR orderno != 1000;
SELECT * FROM order_line 
WHERE item_number ((BETWEEN 1 AND 200) OR (item_number > 1000)) AND ((item_cost NOT IN (1000,2000,3000)) OR (orderno != 1000));

2022-09-29 13:36 UTC, rbEY22 commented on rianboutin/db/queries.sql
> +SELECT * FROM clients WHERE name = 'EY';
![image](https://user-images.githubusercontent.com/113386144/193046279-be14b457-c9ba-4d10-ba71-446689e0da02.png)

2022-09-29 13:36 UTC, rbEY22 commented on rianboutin/db/queries.sql
> +SELECT * FROM clients WHERE name = 'EY';
INSERT INTO clients (name, referred_by)
VALUES ('EY','Arbys');

--Display all client records with “client_name” which has “EY” in it 
SELECT * FROM clients WHERE name LIKE '%EY%';

2022-09-29 13:44 UTC, rbongiorno-ey approved these changes

2022-09-29 13:54 UTC, merged