adding html files from assigned exercises
madhanramu/cdp pull request #78
Opened 2022-09-15 02:39 UTC by mikeippi123

Did the assigned problems given as per the word document. The files added are exercise1_basics.html, exercise2_links.html,  exercise3_images.html, exercise4_semantics.html. There is an addition image attached as well for exercise 3 called photo.jpg.

2022-09-19 15:48 UTC, rbongiorno-ey commented on michaelippolito1/html/exercise3_images.html
> +
**alert** is one of the core JavaScript functions -- alert(message),
If you want to overwrite the default method, you would need to implement the same method signature.
Since you were trying to write a function to fill in the content of the <p id="load> element, you should probably use a better function name. e.g. _imgLoadCompleted._()

2022-09-19 22:01 UTC, madhanramu requested changes
Add screenshots in the PR DESCRIPTION

2022-09-19 23:22 UTC, mikeippi123 commented on michaelippolito1/html/exercise3_images.html
> +
I have made an adjustment to the code and ran a live view to test it. Thank you for the advice!

2022-09-20 16:18 UTC, rbongiorno-ey approved these changes

2022-09-20 20:16 UTC, merged