html and css exercises. 4 html exercises and css 3 image exercise.
madhanramu/cdp pull request #85
Opened 2022-09-15 16:17 UTC by dylangoldstock

2022-09-16 20:09 UTC, dylangoldstock commented
Added js script exercises and attached screen shot. 
<img width="960" alt="jsexercise2" src="https://user-images.githubusercontent.com/113386073/190724697-6054f5cf-0254-4b21-b569-1cb718a99d5a.PNG">

2022-09-19 13:12 UTC, madhanramu requested changes
Add description of the PR with screenshots of the output

2022-09-19 22:08 UTC, madhanramu requested changes

2022-09-19 22:08 UTC, madhanramu commented on dylangoldstock/javascript/js_exercise2.html
> +            }
what will be the output if both a and b are equal? the code should return the output

2022-09-20 18:27 UTC, dylangoldstock reviewed
Fixed issues

2022-09-21 19:56 UTC, madhanramu commented on dylangoldstock/javascript/js_exercise2.html
> +                console.log("entered values are equal")
Print the number like  console.log(a, "is closest to 100");

2022-09-21 19:57 UTC, madhanramu commented on dylangoldstock/javascript/js_exercise4.html
> +            document.getElementById("wishlist").appendChild(p);
the element should be removed from the "products" list if it is added to Wish list

2022-09-21 20:31 UTC, dylangoldstock commented on dylangoldstock/javascript/js_exercise4.html
> +            document.getElementById("wishlist").appendChild(p);
It should work now.

2022-09-21 22:22 UTC, madhanramu requested changes

2022-09-22 19:41 UTC, madhanramu approved these changes

2022-09-22 19:42 UTC, merged