Emmanuel css2
madhanramu/cdp pull request #86
Opened 2022-09-15 16:26 UTC by codewithmanny

![3 picture layout](https://user-images.githubusercontent.com/113386282/191136657-6d65e328-1669-4d3e-bbdd-d125b269dcfa.jpg)
css2-layout-exercise

2022-09-19 22:12 UTC, madhanramu requested changes
Add screenshot of the output in the description

2022-09-19 23:31 UTC, codewithmanny commented
> Add screenshot of the output in the description

addded screenshot of the output in the description

2022-09-22 23:31 UTC, madhanramu approved these changes

2022-09-23 21:06 UTC, madhanramu approved these changes

2022-09-23 21:11 UTC, merged