Emmanuel html
madhanramu/cdp pull request #97
Opened 2022-09-15 20:07 UTC by codewithmanny

done with html exercises

2022-09-19 17:13 UTC, rbongiorno-ey requested changes

2022-09-19 17:13 UTC, rbongiorno-ey commented on emmanuelagyei/css/layout/style.css
> +  /* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
Images are not stacking when the viewport width is less than 500px.
You might want to try with _inline_ display style, instead of _flex_

2022-09-27 22:22 UTC, rbongiorno-ey approved these changes

2022-09-28 00:56 UTC, madhanramu approved these changes

2022-09-28 02:49 UTC, merged